### ISSUE TITLE
Virer le x1

### ISSUE THREAD

**Issue by aurel85** [EpiCanard/GlobalMarketChest#10]
Koin,

Le x1 quand on met en vente n'est pas nécessaire, x2 ou plus à la limite ok et si tu en as besoin mais je trouve cela perturbant surtout le x1 donc s'il pouvait être enlevé ça serait top.

![issue2](https://user-images.githubusercontent.com/24486147/50692374-e6056300-1033-11e9-9622-5acdc30bb236.png)

**Comment by EpiCanard** [comment]
Fixed
