### ISSUE TITLE
[BUG] Anyoing GUI navigation with admin remove item feature

### ISSUE THREAD

**Issue by arturek1666** [EpiCanard/GlobalMarketChest#101]
```markdown

Issue Goal :
 > Bug

Platform:
 > Paperspigot 1.14.4(v:214)

Plugin version :
 > 1.5.0-SNAPSHOT
```
**Description :**
The problem is that if I as an admin wants to remove multiply items from player shop I have to keep repeating the process of typing player name again and again to remove items. 
Gif for evidence of that issue and for better understanding:
![ezgif-6-54be771a342f](https://user-images.githubusercontent.com/1558228/66763636-21c13900-eea0-11e9-9d82-480d59447535.gif)

The same issues happening here to understand you have to watch the gif:
![ezgif-6-a879fa4087f3](https://user-images.githubusercontent.com/1558228/66763679-300f5500-eea0-11e9-8bf5-064755f66f44.gif)

**Comment by EpiCanard** [comment]
Fixed with last dev-build https://www.globalmarketchest-jenkins.fr/job/GlobalMarketChest-dev-builds/22/
