### ISSUE TITLE
[BUG] Not checking the numer of auctions when items are added back when they expired

### ISSUE THREAD

**Issue by arturek1666** [EpiCanard/GlobalMarketChest#102]
```markdown

Issue Goal :
 > Bug

Platform:
 > Paperspigot 1.14.4(v:214)

Plugin version :
 > 1.5.0-SNAPSHOT
```
**Description :**
The problem is that players can have more items added then allowed, example my shop limit is 20 I will add 20 items wait for them to expire add 20 items and then add expired items back with will make it 40 items. This method allows to bypass the limit with I don't think it should.

Because my server has a big limit with is 40 and expires in a long time it's hard for me to give evidence of screenshot ;(

**Comment by EpiCanard** [comment]
While trying to reproduce the bug, I found that expiration of auctions doesn't work with sqlite :')

**Comment by EpiCanard** [comment]
Fixed with last dev-build https://www.globalmarketchest-jenkins.fr/job/GlobalMarketChest-dev-builds/22/
