### ISSUE TITLE
Bug with heads (Head Database plugin)

### ISSUE THREAD

**Issue by aurel85** [EpiCanard/GlobalMarketChest#108]
Hi,

The heads of the plugin we use (Head Database) are counted as damaged items in GMC whereas in previous versions this was not the case.

I use the last version (spigot release) of this plugin, Paper 1.15.2 and the last version of Head Database.

**Comment by EpiCanard** [comment]
I confirm it comes from the last version of Head Database because it works neither for 1.15.2 nor for 1.14.4.
Heads have all a damage set to 3.

**Comment by EpiCanard** [comment]
Fixed
