### ISSUE TITLE
Petit chipotage orthographique

### ISSUE THREAD

**Issue by aurel85** [EpiCanard/GlobalMarketChest#11]
Koin,

Super sympa ce système du nombre d'enchères par bloc mais tu as oublié un petit "s" à enchère ou alors pour faire super précis tu mets enchère(s) vu qu'il peut en avoir qu'une seule, à toi de voir je ne sais pas ce qui est le mieux.
En tout cas autant mettre au pluriel qu'au singulier je pense.

![issue4](https://user-images.githubusercontent.com/24486147/50692428-1b11b580-1034-11e9-96d4-51d826f1e7b9.png)

**Comment by EpiCanard** [comment]
Fixed
