### ISSUE TITLE
Unable to create store.

### ISSUE THREAD

**Issue by XXY218** [EpiCanard/GlobalMarketChest#110]
Issue goal: BUG
Platform: PaperSpigot 1.15.2 #227
Plugin version: 1.7.0

**Description**
Unable to create a store, create a brand, and finally click to create a store, an error will be reported.
https://pastebin.com/snDXMbws

**Comment by EpiCanard** [comment]
Hello :)

It fails when it tries to get the world name from an already created shop.
Have you created a store on another server or in a world that no longer exists?

**Comment by XXY218** [comment]
> Hello :)
> 
> It fails when it tries to get the world name from an already created shop.
> Have you created a store on another server or in a world that no longer exists?

No, I only have one server.

**Comment by EpiCanard** [comment]
Have you changed the name of the world where the shop was ?

**Comment by XXY218** [comment]
> Have you changed the name of the world where the shop was ?

I'm sure there are no changes,there are some shops in this world that can be used, but new ones cannot be created.

**Comment by EpiCanard** [comment]
You use Sqlite or Mysql ? Can you send me your sqlite file or an export of your mysql database ?

**Comment by XXY218** [comment]
> You use Sqlite or Mysql ? Can you send me your sqlite file or an export of your mysql database ?

[GlobalMarketChest.zip](https://github.com/EpiCanard/GlobalMarketChest/files/4552726/GlobalMarketChest.zip)

**Comment by EpiCanard** [comment]
You have a shop created in the "Plot" world, maybe it no longer exists?

Anyway, it shouldn't crash but display something correct, I'll fix it.

In the meantime, if you want a quick fix, you can verify that all of the shops in your database really exist, and if not, delete it from the database.
You can use the tool : DB Browser for SQLite

**Comment by XXY218** [comment]
This world was created using PlotSquared v4. This world has always existed. Could it be because someone suddenly created a store in that world?

Because I have seen other store plugin that are not compatible with this world before.

**Comment by EpiCanard** [comment]
Normally no, it should works in all worlds. Maybe because the world is disabled or not loaded I don't know why.

**Comment by EpiCanard** [comment]
Oh no, this configuration is an old 1.6.0 configuration that I forgot to delete, don't worry about it.

**Comment by EpiCanard** [comment]
@XXY218 
Can you try this version ? 
[GlobalMarketChest-1.7.1.zip](https://github.com/EpiCanard/GlobalMarketChest/files/4554601/GlobalMarketChest-1.7.1.zip)

This should prevent crash. Shops with an unknown world will be displayed with "?" instead of the  world name

**Comment by XXY218** [comment]
It works now, thank you for your help!

**Comment by EpiCanard** [comment]
So when you try to link with a shop that exist (second interface Hen you create a shop) which one is displayed with a "?" ?

**Comment by XXY218** [comment]
No, he now shows "world"

**Comment by EpiCanard** [comment]
Event the plot shop is correctly displayed ?

**Comment by XXY218** [comment]
Yes, he is normal now ... I did n’t know what happened last night

**Comment by EpiCanard** [comment]
Maybe the world was disabled for some reason.
Anyway if the bug comes back, it will not crash :)

I close this issue, since it's fixed
