### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by Nem-developing** [EpiCanard/GlobalMarketChest#112]
Hi ! How can i translate the plugin because therre is no "message.yml" or "message.json". 
Can you explain me ?
Nem.

**Comment by EpiCanard** [comment]
Hello :)
Which language do you want to use ?
There is already some language already supported. You have to change your config variable `General.Lang` to desired language.

**Comment by Nem-developing** [comment]
I whant the french traduction. But i don't realy understand why in the options when i put "fr_FR", plugin can"t launch.

**Comment by EpiCanard** [comment]
Because it is write inside config the possible value is lang-fr_FR.yml

**Comment by Nem-developing** [comment]
Do you have the file please ? IDK Where I can find it ^^

**Comment by EpiCanard** [comment]
In you **config.yml** set the variable **General.Lang** to **lang-fr_FR.yml**

Like that
```yaml
General:
  Lang: "lang-fr_FR.yml"
```

It will automatically extract the french file from the plugin and use it when you will reload the plugin or the server.
