### ISSUE TITLE
Variables not shown correctly

### ISSUE THREAD

**Issue by Srborjaa** [EpiCanard/GlobalMarketChest#115]
Issue goal: Bug
Plugin version: 1.8.1

**Description**

When I search a list of auctions by a certain block, the shown variables in the photo don't work.

**Screenshots**

https://gyazo.com/1fcc4e27fae16c71ab193f69c00a0aa9

**Comment by EpiCanard** [comment]
Fixed in last dev build

**Comment by EpiCanard** [comment]
The fix causes more problems than it fixes
