### ISSUE TITLE
[Issue] Server almost CRASH

### ISSUE THREAD

**Issue by arturek1666** [EpiCanard/GlobalMarketChest#117]
**Issue Goal :**
*Bug*

**Platform:**
SSSpigot 1.16.4 (Tuinity)

**Plugin version :**
GlobalMarketChest v1.9.0 SNAPSHOT

**Description :**
I am getting almost a crashes and it has to do something with sqlite
The error:
https://gist.github.com/arturek1666/b51bc761c5f4c9bed1a4cc0aecc3abcb

**Comment by EpiCanard** [comment]
You seems to have a lot of async task, maybe it is the cause.

Sqlite use a file as storage, if you have a lot of auctions it will really slow the plugin I advice you to use MySQL instead.

Sqlite is for small servers.

**Comment by arturek1666** [comment]
yeah it might be i have about 40-80 players xD, And I am playing to switch to mysql the only problem is how i can safely transport data from sqlite to mysql

**Comment by EpiCanard** [comment]
Hello,

I think I should add commands to move from sqlite to MySQL. Your are not the first one to have that kind of problem ^^'

You can do it when there are a few players or maybe remove permissions from player to be sure they don't create new auctions.

Then switch GMC from sqlite to MySQL in config (you need to create MySQL server and database before) and setup credentials.
Then restart GMC, it will create all tables if all works as expected.

And then you can use a tools to migrate from sqlite to mysql. Maybe use this one ? https://dbconvert.com/sqlite/mysql/

**Comment by arturek1666** [comment]
My sqlite has about 40mb xD

**Comment by EpiCanard** [comment]
Damn it's so big 😮
Good luck !

A warning if there is too much auctions while using sqlite can be an idea too

**Comment by arturek1666** [comment]
My users have time to 01/01/2020 to empty all auctions if not will be deleted, and switched to MySQL that's my solution xD

**Comment by EpiCanard** [comment]
Drastic solution :')

**Comment by EpiCanard** [comment]
I can close ? or you have other question ?
