### ISSUE TITLE
Problème d'actualisation quand on annule toutes les enchères

### ISSUE THREAD

**Issue by aurel85** [EpiCanard/GlobalMarketChest#12]
Koin,

Quand on annule toutes nos enchères via l'interface la nether star pour mettre en vente n'actualise pas notre nombre d'enchère. On peut tout de même mettre une enchère en ligne même si ça affiche 50/50 par exemple donc tout va bien.
Pour que ce chiffre s'actualise correctement il faut sortir de l'interface et y retourner.
Si ça pouvait s'actualiser en direct ça serait top !

**Comment by EpiCanard** [comment]
Fixed
