### ISSUE TITLE
Les potions

### ISSUE THREAD

**Issue by aurel85** [EpiCanard/GlobalMarketChest#13]
Koin,

De base les potions se mettent tous dans la catégorie "Uncraftable Potion" dans Brewing. Il y aurait pas moyen de faire en sorte que chaque potion est sa propre catégorie ?

![issue5](https://user-images.githubusercontent.com/24486147/50692534-88bde180-1034-11e9-9f33-b99d90f726a8.PNG)

Et quand on clique on a ça dedans : 

![capture](https://user-images.githubusercontent.com/24486147/50692560-9f643880-1034-11e9-82cc-74c96d424773.PNG)

**Comment by EpiCanard** [comment]
Je peux pas me permettre de faire au cas par cas.
Je pense faire un system avec des GroupLevels où j'aurais 3 couches et tu pourras choisir entre avoir 1 2 ou 3 couches. 
1 - Tous est au même
2 - C'est globalement l'HDV actuel
3 - Ca regroupe en plus par nom d'item
Si jamais tu comprends pas c'est pas grave je te ferais une démo quand ce sera codé ^^
Et oui j'écris en français car j'ai la flemme de prendre 30 min à te répondre en anglais XD

**Comment by EpiCanard** [comment]
Fixed
