### ISSUE TITLE
1.19.3 support

### ISSUE THREAD

**Issue by xyfwdy** [EpiCanard/GlobalMarketChest#131]

**Comment by EpiCanard** [comment]
Hello,
The fix is coming soon.

**Comment by EpiCanard** [comment]
If you can't wait the official release, you can find a fix for errors on startup that makes the plugin useable in 1.19.3
https://github.com/EpiCanard/GlobalMarketChest/actions/runs/3715358211

There is still work to do before the official release, I need to add support of new creative view and new 1.19.3 items.

**Comment by EpiCanard** [comment]
The support for minecraft 1.19.3 is officially released https://www.spigotmc.org/resources/globalmarketchest-gui-shop-plugin.64921/update?update=482544
