### ISSUE TITLE
GUI broken in MOHIST 1.20.1 serveur

### ISSUE THREAD

**Issue by Linkxx08** [EpiCanard/GlobalMarketChest#140]
```markdown

Issue Goal :
in my mohist 1.20.1 server the interfaces are empty

Platform:
Minecraft serveur Mohist 1.20.1

Plugin version :
Globalmarketchest v1.15.0

Description :
when I launch my server a large error is displayed and in game when I place a panel to create the globalshop the creation interface is empty


Issue goal: Bug
Platform: Minecraft serveur MOHIST 1.20.1
Plugin version: globalmarketchest v1.15.0

screenshot: ![serv](https://github.com/EpiCanard/GlobalMarketChest/assets/157749421/93d2530e-2734-46b8-8851-71aa19ec6a42)

**Comment by EpiCanard** [comment]
Hello,

I don't officially support modded version like Mohist, Catserver or Magma because they have each one there own way to store items.

**Comment by Linkxx08** [comment]
so the plugin cannot work in any case?

**Comment by EpiCanard** [comment]
I quickly made a dirty version for mohist 1.20.1 but there is no long support for this version for now

[GlobalMarketChest-80.zip](https://github.com/EpiCanard/GlobalMarketChest/files/14070283/GlobalMarketChest-80.zip)

**Comment by Linkxx08** [comment]
THANK YOU SO MUCH ! The plugin works perfectly!!!!
I can't thank you enough, it's perfect.
Thank you for paying attention to my problem and good luck!

**Comment by Linkxx08** [comment]
THANK YOU SO MUCH ! The plugin works perfectly!!!!
I can't thank you enough, it's perfect.
Thank you for paying attention to my problem and good luck!
