### ISSUE TITLE
*Bug

### ISSUE THREAD

**Issue by Xbaishu** [EpiCanard/GlobalMarketChest#143]
Issue Goal: Bug 

Platform: Paper 1.21 

Plugin version: GlobalMarketChest v1.15.3

Description
I am experiencing numerous loading errors with the GlobalMarketChest plugin on my 1.21 Paper server. The errors occur during the server startup and prevent the plugin from functioning correctly. I have followed the standard installation procedures and ensured that the plugin is compatible with the Paper 1.21 version. Below are the details of the errors encountered.

Screenshots
Unfortunately, I am unable to provide screenshots at this time, but I have shared the server logs that contain the error details on Pastebin. Here is the link to the logs: https://pastebin.com/AN8BB6LA

**Comment by EpiCanard** [comment]
Duplicate with #144
