### ISSUE TITLE
*Bug  I've found that the plugin is not functioning properly in version 1.21

### ISSUE THREAD

**Issue by Xbaishu** [EpiCanard/GlobalMarketChest#144]
Issue Goal: Bug 

Platform: Paper 1.21 

Plugin version: GlobalMarketChest v1.15.3

Description
I am experiencing numerous loading errors with the GlobalMarketChest plugin on my 1.21 Paper server. The errors occur during the server startup and prevent the plugin from functioning correctly. I have followed the standard installation procedures and ensured that the plugin is compatible with the Paper 1.21 version. Below are the details of the errors encountered.

Screenshots
Unfortunately, I am unable to provide screenshots at this time, but I have shared the server logs that contain the error details on Pastebin. Here is the link to the logs: https://pastebin.com/AN8BB6LA

**Comment by EpiCanard** [comment]
It seems the plug have trouble to get minecraft version. I will check futher

**Comment by Xbaishu** [comment]
If you need more logs from my server, I am very willing to provide them and test them.😊

**Comment by EpiCanard** [comment]
I have what I need, the error comes from here `java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3`

**Comment by EpiCanard** [comment]
Fixed in last release
