### ISSUE TITLE
[BUG] Category and error in console

### ISSUE THREAD

**Issue by WindowsCraft76** [EpiCanard/GlobalMarketChest#147]
Issue Goal :
**Fixed the problem**

Platform:
**spigot 1.21.3**

Plugin version :
**GlobalMarketChest v1.15.5**

Description :
**Items for sale are not displayed in the category except in "Auctions in the last 24 hours" and when I click on the panel this but this error message in the console.**
https://mclo.gs/oEFPmTD

The plugins that I use on my server:

- AFKPlus - [site](https://www.spigotmc.org/resources/afk.35065/)
- BossBar Message - [site](https://www.spigotmc.org/resources/boss-bar-message.53561/)
- DiscordSRV - [site](https://www.spigotmc.org/resources/discordsrv.18494/)
- Floodgate - [site](https://geysermc.org/download/?project=floodgate)
- GeyserMC - [site](https://geysermc.org/download/?project=geyser)
- LuckPerms - [site](https://luckperms.net/)
- Maintenance - [site](https://hangar.papermc.io/kennytv/Maintenance)
- MaxBans - [site](https://dev.bukkit.org/projects/maxbans)
- OpenInv - [site](https://dev.bukkit.org/projects/openinv)
- PlaceholderAPI - [site](https://www.spigotmc.org/resources/placeholderapi.6245/)
- Sethome - [site](https://modrinth.com/plugin/sethome-yottaka)
- SimpleSit - [site](https://www.spigotmc.org/resources/simple-sit-spigot-bukkit-1-8-8-through-1-19.14706/)
- SimpleTpa - [site](https://www.spigotmc.org/resources/simple-tpa.64270/)
- SuperVanich - [site](https://www.spigotmc.org/resources/supervanish-be-invisible.1331/)
- Vault - [site](https://www.spigotmc.org/resources/vault.34315/)
- ProtocolLib - [site](https://www.spigotmc.org/resources/protocollib.1997/)
- Orebfuscator - [site](https://www.spigotmc.org/resources/orebfuscator-anti-x-ray.82710/update?update=549545)
- AntiCreeper - [site](https://www.spigotmc.org/resources/anticreeper-1-17-x-1-21-x-prevent-explosions-damage-caused-by-them.32129/)
- SupremeChat - [site](https://www.spigotmc.org/resources/%E2%9C%85-supremechat-%E2%9C%85-1-16-1-21.108544/)
- SimpleTabList - [site](https://www.spigotmc.org/resources/%E2%98%86-simple-tablist-%E2%98%86%E3%80%8A1-16-x-1-20-x%E3%80%8B-animated-hex-colors.101989/)
- GlobalMarketChest - [site](https://www.spigotmc.org/resources/globalmarketchest-gui-shop-plugin.64921/)
- PlayerPoints - [site](https://www.spigotmc.org/resources/playerpoints.80745/)
- Citizens2 - [site](https://ci.citizensnpcs.co/job/citizens2/)

Issue goal: Fixed the problem 
Platform: spigot 1.21.3
Plugin version: GlobalMarketChest v1.15.5

**Description**
Items for sale are not displayed in the category except in "Auctions in the last 24 hours"
and when I click on the panel this but this error message in the console.
https://mclo.gs/oEFPmTD

**Screenshots**
none

**Comment by EpiCanard** [comment]
Fixed in 1.15.6 release
