### ISSUE TITLE
Naviguer de page en page alors qu'il y a peu d'enchères

### ISSUE THREAD

**Issue by aurel85** [EpiCanard/GlobalMarketChest#16]
Koin,

On peut aller jusqu'à la page 10 (par exemple) alors qu'il y a 2-3 enchères en ligne. Ça serait bien de ne pas pouvoir aller plus loin que la dernière page où on peut trouver des enchères.

**Comment by EpiCanard** [comment]
Fixed

**Comment by EpiCanard** [comment]
The way it is implemented force me to implement a counting system each time there is a paginator. If I don't do a counting system the paginator can't exceed 1 page.
Need to think to a new system fully autmatic.

**Comment by EpiCanard** [comment]
Now it's fully automatic ^^
I close this issue
