### ISSUE TITLE
Suggestion : rajouter un bouton "gratuit" lors du choix du prix de l'item

### ISSUE THREAD

**Issue by aurel85** [EpiCanard/GlobalMarketChest#26]
Tout est dans le titre :)

**Comment by EpiCanard** [comment]
Is it ok for you ?
![free](https://user-images.githubusercontent.com/29657498/51330311-8e291c00-1a77-11e9-8051-174f34bc9f4c.png)
![free_select](https://user-images.githubusercontent.com/29657498/51330312-8e291c00-1a77-11e9-8b35-d9ca0137d93a.png)

**Comment by aurel85** [comment]
I don't understand :/ 

Mais sinon oui :D 

Et ouais, moi je le mettrai tout à droite mais à la limite laisse le comme ça pour ceux qui voudront, juste peut-être le plus à droite possible pour qu'il soit le plus proche du minimum à ajouter.

**Comment by EpiCanard** [comment]
There is now a new boolean flag inside config `Price.DynamicFreePosition` that define if the FreePrice button must be located at the end of line or must be located below center. If the line is full of prices (9 intervals) the button will be located below center.
