### ISSUE TITLE
Petit détail de couleur

### ISSUE THREAD

**Issue by aurel85** [EpiCanard/GlobalMarketChest#28]
Koin,

Ça serait sympa de mettre un peu de couleur ici :)

![capture](https://user-images.githubusercontent.com/24486147/51132456-84fb3d80-1832-11e9-9e67-1997594fe567.PNG)

**Comment by EpiCanard** [comment]
Quoi comme couleur ? Le violet par défaut ?

**Comment by aurel85** [comment]
Ouais pourquoi pas, je t'avoue qu'on pourrait faire comme avec l'autre mais d'autres me dérangeraient pas

**Comment by EpiCanard** [comment]
Azy balance tes couleurs wesh

**Comment by aurel85** [comment]
![capture](https://user-images.githubusercontent.com/24486147/51133188-97767680-1834-11e9-8fe9-a0115a960c47.PNG)

**Comment by EpiCanard** [comment]
Fixed
