### ISSUE TITLE
Duplication enchères (affichage)

### ISSUE THREAD

**Issue by aurel85** [EpiCanard/GlobalMarketChest#30]
Koin,

Avec 2 pioches enchantés anniversaire il y a 2 catégories différentes qui apparaissent alors que ce sont les mêmes.
On a pas détecté ce bug avec d'autres items donc il doit être lié au "GroupLevel"

C'est juste un bug d'affichage, pas de duplication.

**Comment by EpiCanard** [comment]
Ce bug va apparaitre sur tous les items endommagé.
C'est lié à la compatibilité 1.12. Donc soit les items avec dommage seront dans la même catégorie en 1.12 (Andésite dans la même catégories que la stone). Soit je rajoute un flag dans la config pour garder une compatibilité 1.12. Soit j'abandonne le support 1.12 qui n'a pas vraiment été testé jusqu'ici ^^

**Comment by aurel85** [comment]
Abandonne le support 1.12, fais en un plugin full 1.13 et next ;)

**Comment by EpiCanard** [comment]
Ce bug sera présent que pour le GroupLevels set à 3, donc je pense que je vais juste enlever le regroupement par damage. Ce qui rend mas colonne "damage" en base de données inutile , mais bon ^^

**Comment by EpiCanard** [comment]
Fixed
