### ISSUE TITLE
Suggestion : enlever les heures quand c'est à 0

### ISSUE THREAD

**Issue by aurel85** [EpiCanard/GlobalMarketChest#31]
Koin,

Quand il y a 0 heures depuis le début de l'annonce ou avant la fin ça serait plus sympa de l'enlever et d'afficher que les minutes voir de mettre "à l'instant" ou "il y a moins d'1min" si possible. Sinon on gardera le 0 minutes :p

**Comment by EpiCanard** [comment]
Fixed
