### ISSUE TITLE
Bug sur le temps affiché sur les annonces

### ISSUE THREAD

**Issue by aurel85** [EpiCanard/GlobalMarketChest#51]
Koin,

Le temps affiché sur les annonces se reset souvent au bout de 20min.

Ça n'influence pas le temps d'expiration de l'item donc c'est vraiment que du bug d'affichage avec les minutes et secondes en grande partie j'ai l'impression.

**Comment by EpiCanard** [comment]
Fixed.
It was just a wrong % (24 instead of 60) in my minutes calculations.
I also added the full support of var `Options.NumberDaysExpiration` that was missing ^^"
