### ISSUE TITLE
Duplication item

### ISSUE THREAD

**Issue by Sig81** [EpiCanard/GlobalMarketChest#54]
Koin, 

Il est possible de dupliquer n'importe quel item mis en vente à l'hdv y compris les items "clés" (Voir sa money, créer une enchète, retour...)
 
![2019-01-26_23 43 56](https://user-images.githubusercontent.com/38769283/51793682-81699e00-21c4-11e9-8367-8f538ff29e06.png)

Le procédé : J'ai ouvert l'hotel des ventes, ensuite, ayant une connexion assez faible, au moment de créer une nouvelle enchère, j'ai cliqué sur la nether star afin de créer une nouvelle enchère, en attendant le chargement de la page, j'ai pu mettre l'étoile dans mon inventaire et quitter l'hdv. Suite à ça, j'avais l'objet dans mon inventaire, il ne s'agit pas d'un bug graphique car j'ai pu la déplacer dans d'autres coffres et j'ai pu également la passer à d'autres joueurs à travers un drop. 

J'ai testé sur plusieurs items et il s'avère que ça fonctionne à presque tout les coups.

**Comment by EpiCanard** [comment]
Merci pour ton issue, j'essaye de corriger ça avant demain soir :)

**Comment by EpiCanard** [comment]
Fixed
