### ISSUE TITLE
Remove an auction from another player for op

### ISSUE THREAD

**Issue by aurel85** [EpiCanard/GlobalMarketChest#75]
Hi,

My suggestion : 

Ability to remove bids from other players when op (or with permission), this can be very practical in some situations.
Cancel the action to retrieve the item more precisely.

Thank you in advance !

**Comment by EpiCanard** [comment]
Will be in next Release v1.5.0, already available on [dev build 17](https://www.globalmarketchest-jenkins.fr/job/GlobalMarketChest-dev-builds/17/)
