### ISSUE TITLE
Optimize WorldListener

### ISSUE THREAD

**Issue by SpencerSharkey** [EpiCanard/GlobalMarketChest#76]
I think the event listeners around interact/block destroy could be optimized a bit, and I'm testing it out on my fork.

I noticed this plugin was high on my timings report with a lot of active players around those events, so I suggest backing out of the routine as early as possible with a material check.

```diff
--- a/src/main/java/fr/epicanard/globalmarketchest/listeners/WorldListener.java
+++ b/src/main/java/fr/epicanard/globalmarketchest/listeners/WorldListener.java
@@ -125,6 +125,11 @@ public class WorldListener implements Listener {
   public void onPlayerBreakBlock(BlockBreakEvent event) {
     Block block = event.getBlock();
     Player player = event.getPlayer();
+
+    if (!(block.getType() ==  Material.ENDER_CHEST || ShopUtils.isSign(block.getType()))) {
+      return;
+    }
+
     List<BlockFace> attached = Utils.filter(faces, face -> isAttachedTo(block, face));
     if (block.hasMetadata(ShopUtils.META_KEY)) {
       ShopInfo shop = ShopUtils.getShop(block);
@@ -199,7 +204,13 @@ public class WorldListener implements Listener {
     Action action = event.getAction();

     if (event.getClickedBlock() != null && action == Action.RIGHT_CLICK_BLOCK) {
-      ShopInfo shop = ShopUtils.getShop(event.getClickedBlock());
+      Block block = event.getClickedBlock();
+
+      if (block.getType() !=  Material.ENDER_CHEST) {
+        return;
+      }
+
+      ShopInfo shop = ShopUtils.getShop(block);

       if (shop == null)
         return;```

**Comment by EpiCanard** [comment]
Interesting. It was my next goal the plugin optimization. Which tool do you use to see this timing report ?

About your code,
If you look inside the config the linked block is not necessary an enderchest. You can configure it to be any block.

**Comment by SpencerSharkey** [comment]
I use Paper's Timings v2, with high player counts (100+ typically), I'm seeing this plugin use 2-5% of the tick on PlayerInteract event.

I'm just using the enderchest, but I'll update it to check the config material anyways. I can PR this up if you want.

**Comment by EpiCanard** [comment]
Ok, thanks. Can I have the report of your timings ?

Check only materials and sign can have side effect. For example if you create a shop with a block and you remove this block from allowedLinkBlock you will have a shop that can't be removed with linkedBlock.
Yes, you can create a PR that we look that together.

**Comment by EpiCanard** [comment]
No answer. I close this issue
