### ISSUE TITLE
A temporary money storage system

### ISSUE THREAD

**Issue by SN-Koarashi** [EpiCanard/GlobalMarketChest#89]
Issue goal: Suggestion
Platform: Spigot 1.14.3
Plugin version: GlobalMarketChest v1.3.0

**Description**
I hope a temporary money storage system in market because some server will player money save in MySQL not in YML file.
If seller is offline, 
system will add seller's money in YML file after buyer buy seller's item.
And then seller is online now, his money will sync from MySQL.
boom! Seller's money has lost!

This is why I hope this plugin have a temporary money storage system.
Seller can withdraw his money for any time.
...

**Screenshots**
None
...

**Comment by EpiCanard** [comment]
I don't really understand what is the problem.
The plugin doesn't handle the storage of money. It only use Vault which mediates between GlobalMarketChest and the economy plugin (For example: Essentials).

It is the goal of the economy plugin to handle money of offline players.

**Comment by SN-Koarashi** [comment]
I use "MySQL Player Data Bridge" to storage our players money.
But GlobalMarketChest puts players money into EssentialsX yml file.
Lead to players money not correct value because that plugin(MySQL Player Data Bridge) will sync money from MySQL when player online.

**Comment by EpiCanard** [comment]
MySQL Player Data Bridge only sync money, it's not an economy plugin. You must use another plugin for economy.

GlobalMarketChest put nothing inside YML. It only call Vault to give or take money.

If the sync is made only on player login it's more likely an issue with "MySQL Player Data Bridge" but not with GlobalMarketChest.

**Comment by SN-Koarashi** [comment]
Okay, thanks for your answer

**Comment by SN-Koarashi** [comment]
Well...
Can you support enter a command in console when seller sell their item? (Have player variable)

**Comment by EpiCanard** [comment]
What do you want this command do ?
A command to confirm the buy of auctions ?

**Comment by SN-Koarashi** [comment]
Add to config and we can define the value.
It can run command in console when seller sold their items.

**Comment by EpiCanard** [comment]
No I can't.
Because these values are stored inside database and defined by the player when he create his auction.

And for the economy the goal of Vault is not to have to define the command to execute...

And it will not solved your issue. The issue is with MySQL bridge that doesn't sync in real time the money between servers.

**Comment by SN-Koarashi** [comment]
If can't get variable n Vault.
Can we get variable in database?

**Comment by EpiCanard** [comment]
Variable are defined on runtime. When a player buy an auction it take the auction price from the buyer account and give it to the seller.

The seller, the buyer and the price are stored in the auction inside database. So no need to create a custom command that will do exactly the same thing.

**Comment by SN-Koarashi** [comment]
I need to custom command to run MySQL bridge command in console.

**Comment by EpiCanard** [comment]
I see that MySQL bridge add support or multiple shop plugin. It's more likely a request to MySQL bridge to add support of GlobalMarketChest

**Comment by SN-Koarashi** [comment]
So you can't add custom command support?

**Comment by EpiCanard** [comment]
It change all how the economy works inside GlobalMarketChest. I prefer do request to developer of MySQL bridge to add support of GlobalMarketChest

**Comment by SN-Koarashi** [comment]
MySQL bridge avatar seems not reply anyone.
It sounds too bad.

**Comment by EpiCanard** [comment]
We will see. For now only use GlobalMarketChest on one server should work.

**Comment by SN-Koarashi** [comment]
I use this plugin on multi server.
Via bungeecord
