### ISSUE TITLE
Descriptions trop longues

### ISSUE THREAD

**Issue by aurel85** [EpiCanard/GlobalMarketChest#9]
![issue 1_3](https://user-images.githubusercontent.com/24486147/50692331-c2dab380-1033-11e9-9afd-93794d7d1318.png)
![issue1](https://user-images.githubusercontent.com/24486147/50692332-c2dab380-1033-11e9-9dae-987bb8f9c7d8.png)
![issue1_2](https://user-images.githubusercontent.com/24486147/50692333-c2dab380-1033-11e9-95c9-113c3c96af83.png)

**Comment by EpiCanard** [comment]
Fixed
